apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-5lgo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0040-tenant/tkrw-pr712-0075-0040-app/devfile-sample-5lgo@sha256:27c92a8d2026521354d009f0ce61876673edecdfbfc2c608eccbf7c2a93f7a75
        name: my-nodejs
        resources: {}
status: {}
